RboR/config/routes.rb
Rails.application.routes.draw do
  resources :etats
  resources :importances
  resources :taches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

RboR/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

RboR/app/models/etat.rb
class Etat < ApplicationRecord
    has_many :tache
end

RboR/app/models/importance.rb
class Importance < ApplicationRecord
    has_many :tache
end

RboR/app/models/tache.rb
class Tache < ApplicationRecord
    belongs_to :importance
    belongs_to :etat
end

RboR/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RboR/app/controllers/etats_controller.rb
class EtatsController < ApplicationController
  before_action :set_etat, only: %i[ show edit update destroy ]

  # GET /etats or /etats.json
  def index
    @etats = Etat.all
  end

  # GET /etats/1 or /etats/1.json
  def show
  end

  # GET /etats/new
  def new
    @etat = Etat.new
  end

  # GET /etats/1/edit
  def edit
  end

  # POST /etats or /etats.json
  def create
    @etat = Etat.new(etat_params)

    respond_to do |format|
      if @etat.save
        format.html { redirect_to etat_url(@etat), notice: "Etat was successfully created." }
        format.json { render :show, status: :created, location: @etat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @etat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etats/1 or /etats/1.json
  def update
    respond_to do |format|
      if @etat.update(etat_params)
        format.html { redirect_to etat_url(@etat), notice: "Etat was successfully updated." }
        format.json { render :show, status: :ok, location: @etat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @etat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etats/1 or /etats/1.json
  def destroy
    @etat.destroy

    respond_to do |format|
      format.html { redirect_to etats_url, notice: "Etat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etat
      @etat = Etat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def etat_params
      params.require(:etat).permit(:etat)
    end
end

RboR/app/controllers/importances_controller.rb
class ImportancesController < ApplicationController
  before_action :set_importance, only: %i[ show edit update destroy ]

  # GET /importances or /importances.json
  def index
    @importances = Importance.all
  end

  # GET /importances/1 or /importances/1.json
  def show
  end

  # GET /importances/new
  def new
    @importance = Importance.new
  end

  # GET /importances/1/edit
  def edit
  end

  # POST /importances or /importances.json
  def create
    @importance = Importance.new(importance_params)

    respond_to do |format|
      if @importance.save
        format.html { redirect_to importance_url(@importance), notice: "Importance was successfully created." }
        format.json { render :show, status: :created, location: @importance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @importance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /importances/1 or /importances/1.json
  def update
    respond_to do |format|
      if @importance.update(importance_params)
        format.html { redirect_to importance_url(@importance), notice: "Importance was successfully updated." }
        format.json { render :show, status: :ok, location: @importance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @importance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /importances/1 or /importances/1.json
  def destroy
    @importance.destroy

    respond_to do |format|
      format.html { redirect_to importances_url, notice: "Importance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_importance
      @importance = Importance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def importance_params
      params.require(:importance).permit(:descriptif, :codecouleur, :tache_id)
    end
end

RboR/app/controllers/taches_controller.rb
class TachesController < ApplicationController
  before_action :set_tache, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /taches or /taches.json
  def index
    etat = params[:etat]
    @col = params[:col]

    if etat == '1' || etat == '2'
      @taches = Tache.where(etat_id: "#{etat}")
    else
      @taches = Tache.all
    end

    if @col.present?
      if session['ordre'].blank? || session['ordre'] == "DESC"
        session['ordre'] = "ASC"
      else
        session['ordre'] = "DESC"
      end

      if @col == "etat"
        @taches = Tache.order(etat_id: "#{session['ordre']}")
      end

      if @col == "date_crea"
        @taches = Tache.order(created_at: "#{session['ordre']}")
      end

      if @col == "date_prevue"
        @taches = Tache.order(date_prevue: "#{session['ordre']}")
      end
    end
  end

  # GET /taches/1 or /taches/1.json
  def show
  end

  # GET /taches/new
  def new
    @tache = Tache.new
  end

  # GET /taches/1/edit
  def edit
  end

  # POST /taches or /taches.json
  def create
    @tache = Tache.new(tache_params)

    respond_to do |format|
      if @tache.save
        format.html { redirect_to tache_url(@tache), notice: "La tâche a bien été crée." }
        format.json { render :show, status: :created, location: @tache }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tache.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taches/1 or /taches/1.json
  def update
    respond_to do |format|
      if @tache.update(tache_params)
        format.html { redirect_to tache_url(@tache), notice: "La tâche a bien été mise à jour. " } 
        format.json { render :show, status: :ok, location: @tache }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tache.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taches/1 or /taches/1.json 
  def destroy
    ids = Array(params[:id].split(","))
    Tache.where(id: ids).destroy_all 
    respond_to do |format|
      format.html { redirect_to taches_url, notice: "La tâche a bien été détruite."} 
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tache
      @tache = Tache.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tache_params
      params.require(:tache).permit(:id, :descriptif, :created_at, :updated_at,:importance_id, :date_prevue, :etat_id)
    end
end

RboR/app/helpers/application_helper.rb
module ApplicationHelper
end

RboR/app/helpers/etats_helper.rb
module EtatsHelper
end

RboR/app/helpers/importances_helper.rb
module ImportancesHelper
end

RboR/app/helpers/taches_helper.rb
module TachesHelper
    def afficheFleche(colonne)
        if colonne == @col
            fleche = session['ordre'] == 'ASC' ? " ▴" : " ▾"
        else
            fleche = ""
        end

        return fleche
    end
end

RboR/app/views/etats/_etat.html.erb
<div id="<%= dom_id etat %>">
  <p>
    <strong>Etat:</strong>
    <%= etat.etat %>
  </p>

</div>

RboR/app/views/etats/_form.html.erb
<%= form_with(model: etat) do |form| %>
  <% if etat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(etat.errors.count, "error") %> prohibited this etat from being saved:</h2>

      <ul>
        <% etat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :etat, style: "display: block" %>
    <%= form.text_field :etat %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

RboR/app/views/etats/edit.html.erb
<h1>Editing etat</h1>

<%= render "form", etat: @etat %>

<br>

<div>
  <%= link_to "Show this etat", @etat %> |
  <%= link_to "Back to etats", etats_path %>
</div>

RboR/app/views/etats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Etats</h1>

<div id="etats">
  <% @etats.each do |etat| %>
    <%= render etat %>
    <p>
      <%= link_to "Show this etat", etat %>
    </p>
  <% end %>
</div>

<%= link_to "New etat", new_etat_path %>

RboR/app/views/etats/new.html.erb
<h1>New etat</h1>

<%= render "form", etat: @etat %>

<br>

<div>
  <%= link_to "Back to etats", etats_path %>
</div>

RboR/app/views/etats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @etat %>

<div>
  <%= link_to "Edit this etat", edit_etat_path(@etat) %> |
  <%= link_to "Back to etats", etats_path %>

  <%= button_to "Destroy this etat", @etat, method: :delete %>
</div>

RboR/app/views/importances/_form.html.erb
<%= form_with(model: importance) do |form| %>
  <% if importance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(importance.errors.count, "error") %> prohibited this importance from being saved:</h2>

      <ul>
        <% importance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :descriptif, style: "display: block" %>
    <%= form.text_field :descriptif %>
  </div>

  <div>
    <%= form.label :codecouleur, style: "display: block" %>
    <%= form.color_field :codecouleur %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

RboR/app/views/importances/_importance.html.erb
<div id="<%= dom_id importance %>">
  <p>
    <strong>Descriptif:</strong>
    <%= importance.descriptif %>
  </p>

  <p>
    <strong>Codecouleur:</strong>
    <span style="background-color:<%= importance.codecouleur %>"><%= importance.codecouleur %></span>
  </p>

</div>

RboR/app/views/importances/edit.html.erb
<h1>Editing importance</h1>

<%= render "form", importance: @importance %>

<br>

<div>
  <%= link_to "Show this importance", @importance %> |
  <%= link_to "Back to importances", importances_path %>
</div>

RboR/app/views/importances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Importances</h1>

<div id="importances">
  <% @importances.each do |importance| %>
    <%= render importance %>
    <p>
      <%= link_to "Show this importance", importance %>
    </p>
  <% end %>
</div>

<%= link_to "New importance", new_importance_path %>

RboR/app/views/importances/new.html.erb
<h1>New importance</h1>

<%= render "form", importance: @importance %>

<br>

<div>
  <%= link_to "Back to importances", importances_path %>
</div>

RboR/app/views/importances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @importance %>

<div>
  <%= link_to "Edit this importance", edit_importance_path(@importance) %> |
  <%= link_to "Back to importances", importances_path %>

  <%= button_to "Destroy this importance", @importance, method: :delete %>
</div>

RboR/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RtM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

RboR/app/views/taches/_form.html.erb
<%= form_with(model: tache) do |form| %>
  <% if tache.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tache.errors.count, "error") %> prohibited this tache from being saved:</h2>

      <ul>
        <% tache.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">
  <thead>
    <tr>
      <% if action_name == "edit" %>
        <th>État</th>
      <% end %>
      <th>Importance</th>
      <th>Descriptif</th>
      <th>Date prévue</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <%= form.hidden_field :etat_id, :value => 2 %>

      <% if action_name == "edit" %>
        <%= form_for @tache do |form| %>
          <td><%= form.check_box :etat_id, { checked: (@tache.etat_id == 1)}, 1, 2%></td>
        <% end %>
      <% end %>
      
      <td><%= form.collection_select :importance_id, Importance.all, :id, :descriptif, style: "display: block"%></td>
      <td><%= form.text_field :descriptif %></td>
      <td><%= form.datetime_field :date_prevue %></td>

      <% if action_name == "new"%>
        <td><%= form.submit "Créer"%></td>
      <% elsif action_name == "edit" %>
        <td><%= form.submit "Mettre à jour"%></td>
      <% end %>

      <% end %>
    </tr>
  </tbody>
</table>

RboR/app/views/taches/_tache.html.erb
<tr>
  <td>
    <%= tache.etat.etat %>
  </td>

  <td>
    <span style="background-color:<%= tache.importance&.codecouleur %>; white-space: pre;">  </span>
  </td>

  <td>
    <%= tache.descriptif %>
  </td>

  <td>
    <%= l tache.created_at %>
  </td>

  <td>
    <%= l tache.date_prevue %>
  </td>

RboR/app/views/taches/edit.html.erb
<h1>Éditer cette tâche</h1>

<%= render "form", tache: @tache %>

<br>

<div>
  <%= link_to "Retour", taches_path %>
</div>

RboR/app/views/taches/index.html.erb
<h1>Remember the Milk</h1>

<div id="taches">
  <%= link_to "Toutes", "#{request.path}"%> |
  <%= link_to "Tâches effectuées", "#{request.path}?etat=1"%> |
  <%= link_to "Tâches incomplètes", "#{request.path}?etat=2"%> <br><br>
  <table class="table">
    <thead>
      <tr>        
        <th><%= link_to "État#{afficheFleche("etat")}", "#{request.path}?col=etat", class: "link_to-no-deco"%></th>
        <th></th>
        <th>Descriptif</th>
        <th><%= link_to "Date de Création#{afficheFleche("date_crea")}", "#{request.path}?col=date_crea", class: "link_to-no-deco"%></th>
        <th><%= link_to "Date prévue#{afficheFleche("date_prevue")}", "#{request.path}?col=date_prevue", class: "link_to-no-deco"%></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @taches.each do |tache| %>
        <%= render tache %>
          <td>
            <%= link_to "Plus d'infos", tache %>
          </td>
        </tr>
      <% end %>
      <tr hidden id="ajout">
        <%= form_for(Tache.new) do |form| %>
          <td>----------<%= form.hidden_field :etat_id, :value => 2 %></td>
          <td><%= form.collection_select :importance_id, Importance.all, :id, :descriptif, style: "display: block"%></td>
          <td><%= form.text_field :descriptif %></td>
          <td>--------------------</td>
          <td><%= form.datetime_field :date_prevue %></td>
          <td><%= form.submit "Créer"%></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

<br><%= link_to "Créer une tâche", new_tache_path %>
<br><span>--------------------</span>
<br><input type="button" value="Créer tâche dynamique" onclick="afficheCreerTache()">

<script>
  var afficheCreerTache = function() {
    var row = document.getElementById('ajout');
    row.removeAttribute("hidden");
}
</script>

RboR/app/views/taches/new.html.erb
<h1>Créer une tâche</h1>

<%= render "form", tache: @tache %>

<br>

<div>
  <%= link_to "Retour", taches_path %>
</div>

RboR/app/views/taches/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="taches">
  <table class="table">
    <thead>
      <tr>
        <th>État</th>
        <th></th>
        <th>Descriptif</th>
        <th>Date de Création</th>
        <th>Date prévue</th>
      </tr>
    </thead>
    <tbody>
      <%= render @tache %>
      </tr>
    </tbody>
  </table>
</div>

<div>
  <br><%= link_to "Éditer cette tâche", edit_tache_path(@tache) %> |
  <%= link_to "Retour", taches_path %>

  <br><br><%= button_to "Supprimer cette tâche", @tache, method: :delete %>
</div>